# Generated by Django 3.1.2 on 2021-07-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article', models.CharField(max_length=100)),
                ('barcode', models.ImageField(blank=True, upload_to='barcode')),
                ('commentaire', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=12, null=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='barcode')),
            ],
        ),
    ]
